<?php
/**
 * Created by PhpStorm.
 * User: pappu
 * Date: 12/21/2016
 * Time: 5:18 PM
 */include "header.php";
?>
<div class="section section-padding courses-detail">
    <div class="container">
        <div class="courses-detail-wrapper">
            <div class="row">
                <div class="col-md-9 layout-left"><h1 class="course-title">Get started with Project</h1>
                    <div class="course-video">
                        <iframe width="560" height="315" src="https://www.youtube.com/embed/h8VLznJX8p0?rel=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>

                        <div class="clearfix"></div>
                    </div>


                    <div class="course-des">
                        <div class="course-des-title underline">Courses Info</div>
                        <div class="course-des-content"><p>Bike sharing systems are a means of renting bicycles where the process of obtaining membership, rental, and bike return is automated via a network of small locations throughout a city. Using these systems, people are able to rent a bike from one location and return it at a different location on an as-needed basis. Currently, there are over 500 bike-sharing programs around the world. The data generated by these systems makes them attractive for researchers because the duration of travel, departure location, arrival location, and time elapsed is explicitly recorded. Bike sharing systems therefore function as a sensor network, which can be used for studying mobility in a city. In this project, we use historical usage patterns along with weather data to predict bike rental demand.</p>
                            <strong>Domains</strong>
                            <p>Data mining, Machine Learning
                            </p>

                        </div>
                        <div class="news-list">
                            <div class="list-expand-title underline" >Technologies Needed</div>
                            <div class="row">
                                <div class="col-md-12 col-sm-6 col-xs-6">
                                    <p >
                                    <li>Git <a href="git-syllabus.php"> (Syllabus)</a></li>
                                    <li>Java <a href="java-syllabus.php"> (Syllabus)</a></li>
                                    <li>JavaScript <a href="javascript-syllabus.php"> (Syllabus)</a></li>
                                    <li>HTML CSS<a href="html&css-syllabus.php"> (Syllabus)</a></li>
                                    <li>Tomcat</li></p>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!--course syllubus -->
                    <div class="procudure">
                        <div class="underline">
                            <h3>Project Structure</h3>
                        </div>
                        <div class="remaining"><img src="assets/images/projects/remaining.png" alt="" class="img-responsive"></div>
                    </div>
                    <div class="provide">
                        <div class="whatwe underline" >
                            What we provide
                        </div>
                        <ul>
                            <li>Videos on Required technologies by Ravindrababu Ravula</li>
                            <li>Project Implementation Videos by Ravindrababu Ravula</li>
                            <li>Presentation Slides</li>
                            <li>Assignments with solutions</li>
                            <li>12 weeks of expert guidance</li>
                            <li>Assistance to Complete the Documentation</li>
                        </ul>
                    </div>


                </div>
                <!--courses sidebar starts from here-->
                <div class="col-md-3 sidebar layout-right">
                    <div class="row">


                        <div class="clearfix"></div>
                        <div class="popular-course-widget widget col-md-12 sd380">
                            <div class="title-widget">Popular Courses</div>
                            <div class="content-widget">
                                <div class="media">
                                    <div class="media-left"><a href="interviewpreperation.php" class="link"><img src="assets/images/latestcourse/intprep.png" alt="" class="media-image"/></a></div>
                                    <div class="media-right vertical-middle-custom">
                                        <a href="interviewpreperation.php" class="link title">Interview Preperation</a>
                                    </div>
                                </div>
                                <div class="media">
                                    <div class="media-left"><a href="java.php" class="link"><img src="assets/images/latestcourse/java.png" alt="" class="media-image"/></a></div>
                                    <div class="media-right vertical-middle-custom">
                                        <a href="java.php" class="link title">JAVA</a>



                                    </div>
                                </div>
                                <div class="media">
                                    <div class="media-left"><a href="hadoop.php" class="link"><img src="assets/images/latestcourse/raudraHadoop.png" alt="" class="media-image"/></a></div>
                                    <div class="media-right vertical-middle-custom">
                                        <a href="hadoop.php" class="link title">Hadoop</a>



                                    </div>
                                </div>
                                <div class="media">
                                    <div class="media-left"><a href="gate-2018.php" class="link"><img src="assets/images/latestcourse/book2.png" alt="" class="media-image"/></a></div>
                                    <div class="media-right vertical-middle-custom">
                                        <a href="fullstack.php" class="link title">GATE</a>

                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="course-price-widget widget col-md-12 sd380">


                            <div class="content-widget">
                                <div class="course-price-widget-wrapper">
                                    <h1 class="title-widget">Fee</h1>
                                    <div class="#"><p style="font-size: 22px;text-align: center;font-weight: bolder;">INR 30000</p></div>
                                    <div class="row">
                                        <div class="col-md-12 info-row col-sm-12 col-xs-12">
                                            <div class="pull-left title">Length:</div>
                                            <div class="pull-right length">120+</div>
                                        </div>


                                        <div class="col-md-12 info-row col-sm-12 col-xs-12">
                                            <div class="pull-left title">Validity:</div>
                                            <div class="pull-right level">6 Months</div>
                                        </div>

                                    </div>
                                </div>
                                <button class="myBtn btn btn-green"><span>Closed</span></button>
                            </div>
                        </div>


                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
</div>
</div>
<?php
include "footer.php";
?>
<div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
        <span class="close">&times;</span>
        <div style="color:#000000; text-align: left" >
            <p>If you are interested in registering, you can make the payment in the following account either through net banking or at your nearest HDFC bank and email us the transaction id or scan copy of the pay-in-slip.</p>
            <p>Fee for the Complete Project including the required technical courses is INR <strong>30000.00</strong> per project(Please refer to the specific project to know the list of courses included)</p>
            <p>For group registrations(Maximum of 4 members): INR <strong>60000.00</strong></p>
            <table>
                <tbody>
                <tr>
                    <td>Account Name</td>
                    <td>:</td>
                    <td>Raudra Eduservices Private Limited</td>
                </tr>
                <tr>
                    <td>Account Number</td>
                    <td>:</td>
                    <td>50200012182576</td>
                </tr>
                <tr>
                    <td>Account type</td>
                    <td>:</td>
                    <td>Current account</td>
                </tr>
                <tr>
                    <td>Bank</td>
                    <td>:</td>
                    <td>HDFC</td>
                </tr>
                <tr>
                    <td>Branch</td>
                    <td>:</td>
                    <td>JAYABHERI ENCLAVE</td>
                </tr>
                <tr>
                    <td>RTGS / NEFT IFSC</td>
                    <td>:</td>
                    <td>HDFC0003947</td>
                </tr>
                <tr>
                    <td>CITY</td>
                    <td>:</td>
                    <td>HYDERABAD</td>
                </tr>
                </tbody>
            </table>

            <P> After the payment is done, you can email us the screen shot or picture of transaction details or the
                pictures of the bank pay in slip at gate2014.ravindra@gmail.com. Once it is done, you will be given
                access to private GATE lecture videos with in 24 hours. You can watch the videos online anytime,
                anywhere and any number of times. Please note that the videos are not downloadable. Sharing your access
                or trying to sell or distribute videos is a legally punishable offense. Earlier we caught some people
                doing this and they were punished legally and a huge penalty was imposed on them.</P>

        </div>

    </div>

</div>





<script type="text/javascript">
    $(document).ready(function () {
        var temp =0;
        $(".myBtn").click(function () {
            $("#myModal").css('display',"block" );
            temp = 1;
        });

        $(".close").click(function () {
            $("#myModal").css('display',"none" );
            temp = 0;
        });
    });
</script>

</div>


